
<% Fontcolor = "White"
BGC = "Black" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "Black"
BGC = "White" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "White"
BGC = "IndianRed" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LightCoral" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Salmon" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DarkSalmon" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LightSalmon" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Crimson" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Red" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "FireBrick" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DarkRed" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "Black"
BGC = "Pink" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LightPink" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "HotPink" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DeepPink" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Coral" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Orange" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC =  "Gold" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<option style="color:<%=Fontcolor%>; background-color: #FFD666;" value="#FFD666" >Marit Gold</option>

<% BGC =  "Yellow" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC =  "LightYellow" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LemonChiffon" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC =  "PaleGoldenrod" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC =  "Khaki" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC =  "DarkKhaki" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Lavender" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<%   BGC = "Plum" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Violet" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "White"
BGC = "Orchid" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "MediumOrchid" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "MediumPurple" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DarkMagenta" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Purple" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Indigo" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DarkSlateBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<%  Fontcolor = "Black"
BGC = "LimeGreen" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "GreenYellow" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "PaleGreen" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<%  Fontcolor = "White"
BGC = "MediumSeaGreen" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "ForestGreen" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Green" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DarkGreen" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "OliveDrab" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Olive" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DarkOliveGreen" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "black"
BGC = "Aqua" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LightCyan" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "PaleTurquoise" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "White"
	BGC = "CadetBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "SteelBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "black"
BGC = "LightSteelBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LightBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LightSkyBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DeepSkyBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "White"
	BGC = "DodgerBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "CornflowerBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "MediumSlateBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "RoyalBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "MediumBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "DarkBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Navy" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "MidnightBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "black"
BGC = "BlanchedAlmond" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Cornsilk" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "NavajoWhite" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Wheat" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "BurlyWood" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Tan" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "RosyBrown" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "SandyBrown" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->

<option style="color: white; background-color: #761C00;" value="#761C00" >Corsicana Brown</option>
<% BGC = "SandyBrown" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Goldenrod" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "White"
BGC = "Peru" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Chocolate" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "SaddleBrown" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Sienna" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Brown" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Maroon" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% Fontcolor = "Black"
BGC = "Honeydew" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Azure" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "AliceBlue" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "WhiteSmoke" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Seashell" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Ivory" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "AntiqueWhite" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Linen" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LavenderBlush" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "MistyRose" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "Gainsboro" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<% BGC = "LightGrey" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->
<option style="color:<%=Fontcolor%>; background-color: #B8C5CC;" value="#B8C5CC" >Wasatch Grey</option>
<% Fontcolor = "White"
BGC = "SlateGray" %>
<!-- #include file="AdminColorOptionsIncludeInclude.asp" -->


